// Import Express framework to create route handlers
const express = require('express');
const router = express.Router();

// Import the revision controller containing logic for revision schedules
const revisionController = require('../controllers/revision.controller');

// Import authentication middleware to protect routes
const authenticateToken = require('../middleware/auth');

// Route to get revision schedules for a specific workspace and user
router.get('/workspace/:wsId/user/:userId', authenticateToken, revisionController.getRevisions);

// Route to save new revision schedules generated by AI
router.post('/', authenticateToken, revisionController.saveRevisions);

// Route to update the status of a specific revision schedule
router.put('/:id/status', authenticateToken, revisionController.updateStatus);

// Route to delete a specific revision schedule
router.delete('/:id', authenticateToken, revisionController.deleteRevision);

// Export the router to be used in the main application
module.exports = router;
